### ISSUE TITLE
Script php artisan optimize handling the post-update-cmd event returned with error code 255

### ISSUE THREAD

**Issue by nishant-neosoft** [botble/cms-docs#1]
Starting install Botble CMS...
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /Applications/MAMP/htdocs/.../vendor/symfony/debug/Exception/FlattenException.php on line 237

**Comment by sangnguyenplus** [comment]
You have to change `post_max_size` and `max_upload_filesize` in your php.ini
Thanks!
